eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/

---
server:
  port: 8769
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server

---

server:
  port: 8770
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snorlaxy213/remo-blog.git
          search-paths: respo
          username: snorlaxy213
          password: LOVEcoding1314
      label: master
  profiles:
    active: remote
  application:
    name: config-server