spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/remo_user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.user.pojo.po
  configuration:
    #开启DB驼峰命名
    map-underscore-to-camel-case: true
---
server:
  port: 9101
spring:
  profiles: user-one
---
server:
  port: 9102
spring:
  profiles: user-two
eureka:
  client:
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      prefer-ip-address: true