spring:
  application:
    name: user
  datasource:
    # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
    p6spy: true
    # 配置hikari连接池
    hikari:
      # 连接池名称
      pool-name: RemoHikariCP
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 连接池最大连接数，默认是10
      maximum-pool-size:  15
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 数据库连接超时测试
      connection-test-query: SELECT 1
    url: jdbc:p6spy:mysql://localhost:3306/remo_user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin
    jedis:
      pool:
        #连接池中的最小空闲连接
        min-idle: 8
        #连接池中的最大空闲连接，默认值是8
        max-idle: 500
        #连接池最大连接数（负值表示没有限制）
        max-active: 2000
        #连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: 10000
    #Redis服务器连接超时的时间（0代表不超时）
    timeout: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.user.pojo.po
  configuration:
    #开启DB驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    banner: false

feign:
  hystrix:
    enabled: true

remo:
  security:
    # token有效期，单位秒
    jwtTimeOut: 3600

---
# port 9101 - 9110
server:
  port: 9101
spring:
  profiles: user-one
eureka:
  client:
    enabled: false
    service-url:
#      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
      defaultZone: http://server-one:8761/eureka/
    instances:
      prefer-ip-address: true
---
server:
  port: 9102
spring:
  profiles: user-two
eureka:
  client:
    service-url:
      #      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
      defaultZone: http://server-one:8761/eureka/
    instances:
      prefer-ip-address: true