spring:
  application:
    name: article
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/remo_article?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
          username: root
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver

---
server:
  port: 9121
spring:
  profiles: file-one
eureka:
  client:
    enabled: false
    service-url:
      #      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
      defaultZone: http://root:root@localhost:8761/eureka/
    instances:
      prefer-ip-address: true

---
server:
  port: 9122
spring:
  profiles: file-two
eureka:
  client:
    enabled: false
    service-url:
      #      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
      defaultZone: http://root:root@localhost:8761/eureka/
    instances:
      prefer-ip-address: true