server:
  port: 9111
spring:
  application:
    name: article
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://gz-cynosdbmysql-grp-18rg22ad.sql.tencentcdb.com:27005/remo_article?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
          username: root
          password: ROOTadmin!
          driver-class-name: com.mysql.cj.jdbc.Driver
  #        slave:
  #          url: jdbc:mysql://192.168.116.128:3306/remo_article?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  #          username: root
  #          password: root
  #          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    enabled: true # Redis开关/默认关闭
    timeout: 1000
    database: 0
    #主节点的master
    host: 1.14.163.139
    #redis密码
    password: admin
    #主节点的master端口
    port: 6379
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 3 #连接池中的最小空闲连接
        max-wait: 6000 #连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel:
      master: symaster
      # 逗号分隔, 逗号前后不要有空格
      nodes: 1.14.163.139:26379
  secondaryRedis:
    host: 1.14.163.139
    port: 6380
    password: admin
  # 上传文件配置
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件总的最大值
      max-file-size: 10MB # 单个文件的最大值
mybatis-plus:
  # important！！！！！  @MapperScan记得扫描mapper所在包
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.article.pojo.entity
#  configuration:
#    #开启DB驼峰命名
#    map-underscore-to-camel-case: true
common:
  swagger-open: true

eureka:
  client:
    enabled: false
    service-url:
      #      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
    instances:
      prefer-ip-address: true

feign:
  hystrix:
    enabled: true
