# 9111 -9120
server:
  port: 9111
spring:
  application:
    name: article
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/remo_article?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
          username: root
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
  #        slave:
  #          url: jdbc:mysql://192.168.116.128:3306/remo_article?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  #          username: root
  #          password: root
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件总的最大值
      max-file-size: 10MB # 单个文件的最大值
mybatis-plus:
  # important！！！！！  @MapperScan记得扫描mapper所在包
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.article.pojo.entity
#  configuration:
#    #开启DB驼峰命名
#    map-underscore-to-camel-case: true
common:
  swagger-open: true

eureka:
  enabled: true
  client:
    service-url:
      #      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
    instances:
      prefer-ip-address: true

feign:
  hystrix:
    enabled: true
