server:
  port: 8763

spring:
  application:
    # 该服务的名称，同时也是注册到eureka上的应用名称
    name: gateway
  cloud:
    gateway:
      # 关闭gateway，默认为false
      enabled: true
      discovery:
        locator:
          # 是否与服务注册与发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false
          enabled: true
      routes:
        - id: user
          uri: http://user:9101
          predicates:
            - Path=/user/**
          filters:
            # StripPrefix Filter 是一个请求路径截取的功能,StripPrefix=n,n代表截取路径的个数
            - StripPrefix=1
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      # 将自己的IP注册到eureka server，如不配或配置为false，则将微服务所在操作系统的hostname注册到eureka server
      prefer-ip-address: true
