server:
  port: 8763

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # close gateway, default value is true
      enabled: true
      discovery:
        locator:
          # 是否与服务注册与发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false
          enabled: true
      routes:
        - id: user
          uri: http://user:9101
          predicates:
            - Path=/user/**
          filters:
            # StripPrefix Filter 是一个请求路径截取的功能,StripPrefix=n,n代表截取路径的个数
            - StripPrefix=1
eureka:
  client:
    enabled: true
    service-url:
      #      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
      defaultZone: http://server-one:8761/eureka/
    instances:
      prefer-ip-address: true
