spring:
  application:
    name: seckill
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

---
server:
  port: 8791
spring:
  profiles: seckill-one
eureka:
  client:
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      prefer-ip-address: true

---
server:
  port: 8792
spring:
  profiles: seckill-two
eureka:
  client:
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      prefer-ip-address: true
