spring:
  application:
    name: seckill
  datasource:
    url: jdbc:mysql://localhost:3306/remo_seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    enabled: true # Redis开关/默认关闭
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #redis密码
    password: admin
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

---
server:
  port: 8791
spring:
  profiles: dev

---
server:
  port: 8792
spring:
  profiles: seckill-one
eureka:
  client:
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      prefer-ip-address: true

---
server:
  port: 8793
spring:
  profiles: seckill-two
eureka:
  client:
    service-url:
      defaultZone: http://server-one:8761/eureka/,http://server-two:8762/eureka/
    instances:
      prefer-ip-address: true
